image: node:12-alpine

before_script:
    - npm install

stages:
    - sonar analysis
    - test
    - lint
    - build
    - build image

sonarqube:
    image: sonarsource/sonar-scanner-cli
    stage: sonar analysis
    before_script: []
    script:
        - sonar-scanner -Dsonar.projectKey=collection-editor-frontend -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.whiteaster.com -Dsonar.login=a4de2a3c0c4533331b6a1d3ca7afbbc1a3ecffa7
    only:
        - master

lint:
    stage: lint
    script:
        - npm run lint

tests:
    stage: test
    script:
        - npm run test

build:
    stage: build
    script:
        - npm run build:prod

Build production image:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: ['']
    stage: build image
    before_script: []
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:$latest
    only:
        - tags
        - master

Build development image:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: ['']
    stage: build image
    before_script: []
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:development
    only:
        - development